version: '3.8'

services:
  quantum_storage:
    image: quantum/storage:latest
    container_name: quantum_storage
    ports:
      - "432:432"
    volumes:
      - ./quantum-data:/data
      - ./config:/config
      - ./certs:/certs
    environment:
      - QUANTUM_FREQUENCY=432.0
      - QUANTUM_ROLE=STORAGE
      - QUANTUM_NODE_ID=synology
      - SSL_ENABLED=true
    networks:
      - quantum_net

  quantum_bridge:
    image: quantum/bridge:latest
    container_name: quantum_bridge
    ports:
      - "528:528"
    environment:
      - QUANTUM_FREQUENCY=528.0
      - QUANTUM_ROLE=BRIDGE
      - QUANTUM_NODE_ID=bridge
    networks:
      - quantum_net

  quantum_processor:
    image: quantum/processor:latest
    container_name: quantum_processor
    ports:
      - "768:768"
    environment:
      - QUANTUM_FREQUENCY=768.0
      - QUANTUM_ROLE=PROCESSOR
      - QUANTUM_NODE_ID=lenovo_p1
    networks:
      - quantum_net

networks:
  quantum_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
